---
title: "JSON Match Statistics"
author: "Jack Peacock"
date: "20 May 2015"
output: html_document
---

# Match Statistics Report

```{r echo=FALSE, results=hide}
## Set the working directory of the game you are interested in

setwd("~/Documents/Darts Business/JSON Data/Premier League/Week 15/lewisanderson/")

## Set the name of the players

playerA = "lewis"
playerB = "anderson"

## This following code does not need to be touched it will produce the statistics.

library(rjson); library(Hmisc)
AJSON <- fromJSON(file=paste(playerA, ".json", sep = ""))
BJSON <- fromJSON(file=paste(playerB, ".json", sep = ""))

## This function is needed to generate the data frames

createDataFrame <- function(JSONList) {
        bed <- vector(); dartScore <- vector(); aimedat <- vector()
        leg <- vector(); sB4Dart <- vector(); sAfDart <- vector()
        number <- vector(); average <- vector();
        algorithm <- vector();
        
        for (n in 1:length(JSONList)) {
                bed <- c(bed, JSONList[[n]][[1]])
                dartScore <- c(dartScore, JSONList[[n]][[2]])
                aimedat <- c(aimedat, JSONList[[n]][[3]])
                leg <- c(leg, JSONList[[n]][[5]])
                sB4Dart <- c(sB4Dart, JSONList[[n]][[6]])
                sAfDart <- c(sAfDart, JSONList[[n]][[7]])
                number <- c(number, JSONList[[n]][[8]])
                average <- c(average, JSONList[[n]][[9]])
                algorithm <- c(algorithm, JSONList[[n]][[4]])
        }
        
        return(data.frame(number, leg, dartScore, bed, aimedat, sB4Dart, sAfDart, average, algorithm))
}

adf <- createDataFrame(AJSON)
bdf <- createDataFrame(BJSON)
```

```{r echo=FALSE}
paste("These are the Statisitcs for the match between", capitalize(playerA), capitalize(playerB))
```

## Player A

Triple percentage

```{r echo=FALSE}
playerA



```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
