setwd("./Desktop//Darts Business")
library(rjson)
AJSON <- fromJSON(file="RVB.json")
BJSON <- fromJSON(file="VvdV.json")
bed <- vector()
dartScore <- vector()
aimedat <- vector()
leg <- vector()
sB4Dart <- vector()
sAfDart <- vector()
number <- vector()
average <- vector()

for (n in 1:length(AJSON$darts)) {
        bed <- c(bed, AJSON[[2]][[n]]$bed)
        dartScore <- c(dartScore, AJSON[[2]][[n]]$dartScore)
        aimedat <- c(aimedat, AJSON[[2]][[n]]$aimedat)
        leg <- c(leg, AJSON[[2]][[n]]$leg)
        sB4Dart <- c(sB4Dart, AJSON[[2]][[n]]$sB4Dart)
        sAfDart <- c(sAfDart, AJSON[[2]][[n]]$sAfDart)
        number <- c(number, AJSON[[2]][[n]]$number)
        average <- c(average, AJSON[[2]][[n]]$average)
}
Adf <- data.frame(number, leg, dartScore, bed, aimedat, sB4Dart, sAfDart, average)
bed <- vector()
dartScore <- vector()
aimedat <- vector()
leg <- vector()
sB4Dart <- vector()
sAfDart <- vector()
number <- vector()
average <- vector()
for (n in 1:length(BJSON$darts)) {
        bed <- c(bed, BJSON[[2]][[n]]$bed)
        dartScore <- c(dartScore, BJSON[[2]][[n]]$dartScore)
        aimedat <- c(aimedat, BJSON[[2]][[n]]$aimedat)
        leg <- c(leg, BJSON[[2]][[n]]$leg)
        sB4Dart <- c(sB4Dart, BJSON[[2]][[n]]$sB4Dart)
        sAfDart <- c(sAfDart, BJSON[[2]][[n]]$sAfDart)
        number <- c(number, BJSON[[2]][[n]]$number)
        average <- c(average, BJSON[[2]][[n]]$average)
}

Bdf <- data.frame(number, leg, dartScore, bed, aimedat, sB4Dart, sAfDart, average)